PE-672: Use object params on ArDrive class methods for extensibility
ardriveapp/ardrive-cli pull request #146
Opened 2021-11-09 22:30 UTC by fedellen

This PR refactors all of the public methods in the ArDrive and ArDrive anonymous classes to use the object de-structuring pattern on parameters. This will allow us to further extend each of these methods without resorting to long and potentially error-prone positional params.

The destination branch is a newly created integration branch between the safe types branch and the upload conflict branch to avoid conflicts when they merge

2021-11-09 22:50 UTC, arielmelendez commented on src/ardrive.ts
> +	public async getDriveIdForFileId({ fileId }: GetDriveIdForFileIdParams): Promise<DriveID> {
Seems like overkill here.

2021-11-10 02:20 UTC, fedellen commented on src/ardrive.ts
> +	public async getDriveIdForFileId({ fileId }: GetDriveIdForFileIdParams): Promise<DriveID> {
b26cf47

2021-11-10 02:48 UTC, arielmelendez requested changes
Test

2021-11-10 02:51 UTC, arielmelendez approved these changes

2021-11-10 19:05 UTC, merged