PE-463: download folder
ardriveapp/ardrive-cli pull request #148
Opened 2021-11-10 15:33 UTC by matibat

2021-11-16 18:59 UTC, matibat reviewed
Please implement in this PR the tests for the stream class

2021-11-16 18:59 UTC, matibat commented on src/ardrive_anonymous.ts
> +		// const children = folderEntityDump.slice(1);
remove unused code

2021-11-16 18:59 UTC, matibat commented on src/folderHierarchy.ts
> +import { RootFolderID } from './utils/arfs_builders/arfs_folder_builders';
**ToDo** revert these changes

2021-11-18 20:30 UTC, matibat reviewed
**For the reviewer**
Have in mind all the features implemented here for ArDrive and ArFSDAO are moved to https://github.com/ardriveapp/ardrive-core-js/pull/83

2021-11-18 20:31 UTC, matibat commented on src/ardrive_anonymous.ts
> +		// const children = folderEntityDump.slice(1);
ArDrive was de-coupled from CLI: https://github.com/ardriveapp/ardrive-core-js/pull/83

2021-11-23 23:37 UTC, arielmelendez commented on src/commands/download_folder.ts
> +		{ name: DriveIdParameter, required: false },
Ooooh interesting.

2021-11-23 23:45 UTC, arielmelendez commented on src/commands/download_folder.ts
> +		const localFilePath = parameters.getRequiredParameterValue(LocalFilePathParameter, resolve);
What features of `resolve` are you trying to lean on here?

2021-11-23 23:46 UTC, arielmelendez commented on src/commands/download_folder.ts
> +				dryRun
How a downloading dry run work?

2021-11-23 23:47 UTC, arielmelendez commented on src/commands/download_folder.ts
> +			await ardrive.downloadPublicFolder(folderId, maxDepth, localFilePath);
If dry run is really a thing, why can't we do it with public folders?

2021-11-23 23:47 UTC, arielmelendez commented on src/utils/stream_decrypt.ts
> +export class StreamDecrypt extends Transform {
Should this still be here? Isn't it in the core PR now?

2021-11-23 23:48 UTC, arielmelendez requested changes
A few questions.

2021-12-03 14:48 UTC, matibat commented
Outdated

2021-12-03 14:48 UTC, closed without merging