feat(retry tx): Initialize retry-tx command PE-1246
ardriveapp/ardrive-cli pull request #275
Opened 2022-04-29 13:11 UTC by fedellen

This PR adds the CLI side functionality for the `retry-tx` command.

Currently in draft, still need to add the README component

2022-05-02 13:57 UTC, karlprieb commented on README.md
> +With the data transaction ID and the file data is recovered a file simply use the `retry-tx` command:
I'm having a hard time to understand this phrase. I feel it doesn't make sense, maybe because English is not my main language.

2022-05-06 14:27 UTC, karlprieb approved these changes

2022-05-12 04:23 UTC, arielmelendez commented on README.md
> +Using the CLI, when the transaction post has succeeded but the chunk upload fails due to the process crashing the data transaction's ID could be lost. But a user has a few options to recover this ID.
```suggestion
Using the CLI, when the transaction post has succeeded but the chunk upload step fails, the data transaction's ID could be lost. There are a few options to recover this ID. If the failed transaction is the most recent one sent from a wallet, the transaction ID can be quickly recovered with the `ardrive last-tx -w /path/to/wallet` command. Other options for finding the partially uploaded transaction's ID include: 
- Using an Arweave gateway GQL http endpoint to search for transactions that belong to the wallet. See this [Arweave GQL Guide][https://gql-guide.vercel.app/#owners] for more info.
- Browse the recent  transactions associated with the wallet via a block explorer tool like [ViewBlock][viewblock].
```

2022-05-12 04:25 UTC, arielmelendez commented on README.md
> +In order to re-seed the chunks to an unbundled ArFS data transaction, a user must have the data transaction ID, the original file data, and a destination folder ID or a valid file ID for the file. Wi
```suggestion
In order to re-seed the chunks for an unbundled ArFS data transaction, a user must have the data transaction ID, the original file data, and either a destination folder ID or a valid file ID for the file. Supply that information to the `retry-tx` command like so:
```

2022-05-12 04:26 UTC, arielmelendez commented on README.md
> +**Note: Retry feature is currently only available for PUBLIC unbundled file transactions. It is also perfectly safe to mistakenly re-seed the chunks of a healthy transaction, the transaction will rem
```suggestion
**Note: Retry feature is currently only available for PUBLIC unbundled file transactions. It is also perfectly safe to mistakenly re-seed the chunks of a healthy transaction, the transaction will remain stable and the wallet balance will not be affected.**
```

2022-05-12 04:27 UTC, arielmelendez commented on src/commands/retry_tx.ts
> +		{ name: TransactionIdParameter, description: 'The data transaction id in which to retry' },
```suggestion
		{ name: TransactionIdParameter, description: 'The transaction ID of the data transaction to retry' },
```

2022-05-12 04:29 UTC, arielmelendez commented on src/commands/retry_tx.ts
> +		const fileId = parameters.getParameterValue(FileIdParameter, EID);
We should assert here to the user that one or the other is provided.

2022-05-12 04:31 UTC, arielmelendez requested changes
Looks really good! Please review my suggested updates.

2022-05-17 18:53 UTC, matibat approved these changes
It looks great! Glad we'll have this new command 🥳

2022-05-17 18:53 UTC, matibat commented on package.json
> +		"ardrive-core-js": "1.13.0-alpha-1",
Reminder to set the correct version after we release core

2022-05-17 18:53 UTC, arielmelendez submitted a review, later dismissed

2022-05-17 19:34 UTC, matibat approved these changes
🚀

2022-05-17 19:35 UTC, merged