PE-318: list drive command
ardriveapp/ardrive-cli pull request #45
Opened 2021-09-24 20:08 UTC by matibat

2021-09-29 23:27 UTC, matibat commented on src/arfsdao.ts
> +		if (folderId === 'root folder') return '/';
Remove this
```suggestion
```

2021-09-29 23:27 UTC, matibat commented on src/commands/list_folder.ts
> +				new ArDriveCommunityOracle(cliArweave),
Shouldn't we be getting these from injection? Maybe move it to the context class???

2021-09-29 23:30 UTC, matibat commented on src/commands/list_folder.ts
> +				new ArDriveCommunityOracle(cliArweave),
For this question, I think you are the guy @arielmelendez! ;)

2021-10-05 19:28 UTC, matibat commented on src/commands/list_folder.ts
> +				new ArDriveCommunityOracle(cliArweave),
Outdated. Closing.

2021-10-06 03:44 UTC, arielmelendez commented on src/arfsdao.ts
> +	): Promise<ArFSPublicFileOrFolderWithPaths[]> {
• Add validation for maxDepth value (>= 0).
• Update docblock

2021-10-06 03:52 UTC, arielmelendez commented on src/arfsdao.ts
> +		maxDepth: number,
Validate max depth and update docblocks.

2021-10-06 04:07 UTC, arielmelendez commented on src/commands/list_drive.ts
> +		const maxDepth = 0;
Why is the default behavior to list a max depth of 0? As per the manpage:
```
list-drive:
  • Gets all ArFS Metadata and Txids for the files and folders within this drive
  --drive-id: the ArFS drive ID for the drive
  --drive-password: the drive password for drive of the folder identified by --drive-id
  • Required only for folders residing in private drives
  • Can NOT be used in conjunction with --drive-key
  --drive-key: the drive key for the parent drive of the folder identified by --folder-id
  • Required only for folders residing in private drives
  • Can NOT be used in conjunction with --drive-password
  --get-all-revisions: (OPTIONAL) gets every revision of each ArFS entity within this drive
```
most notably `Gets all ArFS Metadata and Txids for the files and folders within this drive`, key word `all`. So I believe the max depth value here should be Number.MAX_SAFE_INTEGER (or Number.POSITIVE_INFINITY).

2021-10-06 05:07 UTC, arielmelendez commented on src/commands/list_drive.ts
> +	parameters: [DriveIdParameter, SeedPhraseParameter, WalletFileParameter],
You're missing the drive password and drive key parameters for private drives. This doesn't work for private drives.

2021-10-06 05:43 UTC, arielmelendez requested changes
This code needs to be tested. It's not working for me locally.

2021-10-06 06:36 UTC, arielmelendez commented on src/commands/list_drive.ts
> +	parameters: [DriveIdParameter, SeedPhraseParameter, WalletFileParameter],
c4e2a90

2021-10-06 06:53 UTC, arielmelendez commented on src/arfsdao.ts
> +		maxDepth: number,
eee1dba

2021-10-06 07:46 UTC, arielmelendez approved these changes

2021-10-06 07:47 UTC, merged