PE-451: Getter function for driveKey
ardriveapp/ardrive-cli pull request #51
Opened 2021-09-28 13:40 UTC by matibat

2021-09-30 00:42 UTC, arielmelendez commented
Why is `.github/workflows/test_and_build.yml` deleted in this PR?

2021-09-30 00:45 UTC, arielmelendez commented on src/ardrive.ts
> +		driveKey: DriveKey,
Having a real drive key here is not necessary.

2021-09-30 06:48 UTC, arielmelendez commented on src/ardrive.ts
> +	async getPrivateFolderMetaData(folderId: FolderID): Promise<ArFSPrivateFolderBuilder> {
A few problems here:
1) This function proclaims to return metadata, but in actuality it returns a builder type. Builders are NOT trustworthy objects meant for data bearing. They are intended to be short-lived objects whose brief lifespan is spent collecting fragmented data in order to build an object. So this is a confusing API that seems easy to use *incorrectly*.
2) The only usage I've found for this in the source is indeed using it incorrectly. It gets a builder (which, at construction time, doesn't do anything except store a few pieces of data and an Arweave reference) and then tries to immediately check for a driveId on it which certainly wouldn't exist yet, and which presumably would throw an exception. And in fact when I tested it, that's exactly what happened:
```
yarn ardrive list-folder  --parent-folder-id 4bf26af6-6b5d-4675-b9a7-11ca634b6d3a --wallet-file ./CLI_TEST_arweave-keyfile-g1hzNXVbh2M6LMQSUYp7HgkgxdadYqYEfw-HAajlms0.json --drive-password "mycoolpassword123"
(node:33978) UnhandledPromiseRejectionWarning: Error: Could not get driveId of private folder
```
The ArDrive layer should probably have nothing to do with ArFS-type builders. Can you please explain what you were trying to accomplish?

2021-09-30 06:50 UTC, arielmelendez commented on src/arfsdao.ts
> +	async getPublicDriveMetaData(driveId: string): Promise<ArFSPublicDriveBuilder> {
Same comment here about a confusing API that's leaking builders without explanation.

2021-09-30 06:53 UTC, arielmelendez commented on src/arfsdao.ts
> +	}
Needs whitespace between functions (although I'm not convinced these functions should have been broken up in the first place).

2021-09-30 06:55 UTC, arielmelendez commented on src/utils/arfs_builders/arfs_builders.ts
> +	protected abstract buildEntity(driveKey?: DriveKey): Promise<T>;
This is leaking subtype implementation details. We can't do this. The drive keys should be passed to the constructors of private subtypes only and cached for later usage.

2021-09-30 06:57 UTC, arielmelendez commented on src/arfsdao.ts
> +				return fileBuilder.build();
Why did you get rid of the node data? Without the node data, it will cause a whole new wasted call for GQL data :(

2021-09-30 07:00 UTC, arielmelendez requested changes
Things I like about this PR:
• Removing boilerplate for key generation from a lot of places. I think that's going to be super helpful to the architecture long-term.

Things that need work:
• Leaking of implementation details from lower layers
• Things that have broken functionality (and were easily manually testable given a quick risk impact analysis)
• Things that make the code less efficient (i.e. redundant network calls).

Let's try to catch up on this PR in the morning at some point.

2021-10-01 02:44 UTC, matibat commented
Some files in this PR were deleted after a bad merge, instead of rebase, I created another PR on which i cherry-picked the initial commit and manually made the merge again: see #54

2021-10-01 02:44 UTC, closed without merging